# -*- coding: utf-8 -*-
"""Data Science Seminar 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7nVLOyR-lonPfjp5O3bNeoSkuK8WXo4
"""

!pip install transformers datasets

import torch
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

# Loading dataset and tokenizer
dataset = load_dataset("imdb")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(examples):
    # we want the data to be the same size each time but some reviews are shorter
    # if any are less than max_length, we will add zeros to the end of it until
    # it is the same length as max_length (padding="max_length")
    # if any are longer than max_length, then
    # we truncate it - i.e. delete any characters after max_length is reached.
    return tokenizer(examples["text"], padding="max_length", truncation=True)

# tokenize the data
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Here we have tokenised our data using BERT, i.e. converted the text documents
# to a vector format where each document is now a set of vectors that represents the semantic meaning of the text.

# Embedding-Only Model with Custom Head
class CustomHeadModel(nn.Module):
  def __init__(self, embedding_dim, num_lables):
    super(CustomHeadModel, self).__init__()
    self.embedding_dim = embedding_dim # input
    self.linear1 = nn.Linear(embedding_dim, 64) # linear layer
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(64, num_lables) # linear layer - binary output

  def forward(self, embeddings):
    x = self.linear1(embeddings)
    x = self.relu(x)
    return self.linear2(x)

# create a model from the pretrained embeddings
model_embeddings = AutoModel.from_pretrained("bert-base-uncased")

# get the size of the embeddings (number of dimensions)
embedding_dim = model_embeddings.config.hidden_size

num_labels = 1 # Binary classification (positive: 0, negative: 1)

# setup the custom head to take embeddings size as input and labels as output
# note this time we are doing binary classification with two neurons to keep
# num_labels as flexible and something we could change to a higher number of labels
# this works the same way as output=1. Its slightly less efficient but fine
custom_head = CustomHeadModel(embedding_dim, num_labels)

"""Here we have a similar codebase to the one we have seen before.
The difference is essentialy at the input layer.
Rather than feeding in raw data, we have fed in the embeddings from BERT.

In our model the input layer is based on the shape of the embeddings we create
with BERT and incorporate into our architecture via AutoModel.
We then add a two layer DNN with ReLU and 64 neurons in the first layer and then we build our output layer as one neuron.
"""

# Embeddings-only prediction (with training of the classification head)

# Freeze the embeddings
for param in model_embeddings.parameters():
    param.requires_grad = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_embeddings.to(device) # add embedding model to GPU
custom_head.to(device) # add custom head to GPU

optimizer = optim.AdamW(custom_head.parameters(), lr=5e-5, weight_decay=0.0005) # Only optimise the custom head
criterion = nn.BCEWithLogitsLoss()

# use a subset of 1,000 random records for demonstration
small_train_dataset = tokenized_datasets["train"].shuffle().select(range(1000))

# Data is a list including:
# 1. id of words
# 2. attention mask
# 3. label

# Custom collate function to handle lists which DataLoader doesn't do automatically
def custom_collate(batch):
    input_ids = torch.tensor([item['input_ids'] for item in batch])
    attention_mask = torch.tensor([item['attention_mask'] for item in batch])
    labels = torch.tensor([item['label'] for item in batch])
    return {'input_ids': input_ids, 'attention_mask': attention_mask, 'label': labels}

train_loader = DataLoader(small_train_dataset, shuffle=True, batch_size=16, collate_fn=custom_collate)

"""Now we have the model we can set up for training. At the very start of the code, we have made the embeddings part of the model non-trainable (by setting these parameters as "requires_grad = False"). This means during training only the weights in the custom head will be updated in optimisation.

We specify a loss function (BinaryCrossEntropy becuase we are using one neuron as output).

We create a DataLoader as before. The only difference is we have a customer collate function because our embedding output will effectively be a list each time including id's, attention masks and labels. In the code above this, we load in a subset of the data (1,000 rows) to reduce training time.
"""

num_epochs = 10

custom_head.train()

for epoch in range(num_epochs):
    for batch in train_loader:
        epoch_loss = 0 # reset loss

        # add data to GPU
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        # Labels need to be float and unsqueezed for BCEWithLogitsLoss
        labels = batch['label'].to(device).float().unsqueeze(1)

        with torch.no_grad(): # Freeze the bert/embeddings model
            embeddings = model_embeddings(input_ids=input_ids, attention_mask=attention_mask).pooler_output

        optimizer.zero_grad()
        logits = custom_head(embeddings) # get logits for custom head
        loss = criterion(logits, labels) # get loss for custom head
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {round(epoch_loss/len(train_loader), 4)}")

# Predictions

example_text = "This is a great movie!"
encoded_input = tokenizer(example_text, return_tensors="pt").to(device)
with torch.no_grad():
    embeddings = model_embeddings(**encoded_input).pooler_output
    logits = custom_head(embeddings)

    # select the highest probability neuron as the prediction
    predictions = torch.argmax(logits, dim=1) # dim 0 is neurons, dim 1 is probability of each

    # print result
    print_label = "positive" if predictions.item() == 0 else "negative"
    print(f"The sentiment of the review is {print_label}")

# Fine-tuning the Model with the Custom Head

# Reset the custom head so it is untrained
custom_head = CustomHeadModel(embedding_dim, num_labels)

# combine the embeddings model and custom head into one model
model_fine_tune = nn.Sequential(model_embeddings,custom_head)
model_fine_tune.to(device) # add the combined model to GPU

# this time optimise all parameters
optimizer = optim.AdamW(model_fine_tune.parameters(), lr=5e-5, weight_decay=0.0005)
criterion = nn.BCEWithLogitsLoss()

# use a subset of 1,000 records for demonstration
small_train_dataset = tokenized_datasets["train"].shuffle().select(range(1000))

# Custom collate function to handle lists which DataLoader doesn't do automatically
def custom_collate(batch):
    input_ids = torch.tensor([item['input_ids'] for item in batch])
    attention_mask = torch.tensor([item['attention_mask'] for item in batch])
    labels = torch.tensor([item['label'] for item in batch])
    return {'input_ids': input_ids, 'attention_mask': attention_mask, 'label': labels}

train_loader = DataLoader(small_train_dataset, shuffle=True, batch_size=16, collate_fn=custom_collate)

# Here we have reset the model - reverted the weights of the custom head back to zero (actually random, but the same meaning).

# Training the model

model_fine_tune.train()
for epoch in range(num_epochs): #train for 3 epochs
  for batch in train_loader:
    epoch_loss = 0
    input_ids = batch['input_ids'].to(device)
    attention_mask = batch['attention_mask'].to(device)
    labels = batch['label'].to(device).float().unsqueeze(1)

    optimizer.zero_grad()

    # Pass input_ids and attention_mask to the first module in the sequence (model_embeddings)
    # and then pass its output to the next module (custom_head)
    outputs = model_fine_tune[1](model_fine_tune[0](input_ids=input_ids, attention_mask=attention_mask).pooler_output)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    epoch_loss += loss.item()

  print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {round(epoch_loss/len(train_loader), 4)}")

example_text = "This is a terrible movie!"
encoded_input = tokenizer(example_text, return_tensors="pt").to(device) # covert example to tokens

with torch.no_grad():
    # Pass input_ids and attention_mask to the first module in the sequence (model_embeddings)
    # and then pass its output to the next module (custom_head)
    # **encoded_input means unpack the list of items
    outputs = model_fine_tune[1](model_fine_tune[0](**encoded_input).pooler_output) # Pass encoded_input as keyword arguments

    # select the highest probability neuron as the prediction
    predictions = torch.argmax(outputs, dim=1)

    # print result
    print_label = "positive" if predictions.item() == 0 else "negative"
    print(f"Prediction for '{example_text}': {print_label}")